//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleIV
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1103314_Dealer
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string OwnersName { get; set; }
        public string OwnersSurName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string VBrand { get; set; }
        public string VModel { get; set; }
        public string VYear { get; set; }
        public string VColor { get; set; }
        public string VVIN { get; set; }
        public string VLicensePlate { get; set; }
        public System.DateTime SeaboardDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
